default:
  setup: "setup/global/setup.R"
  knit_engines: "setup/global/knit_engines.R"
  conflicts: "setup/global/conflicts.R"
  functions: "setup/global/functions.R"
  packages: "setup/global/packages.R"
  inputs: "setup/global/inputs.R"
  visuals: "visuals/"
  summaries:
    metadata: "../summaries/metadata/"
  tmp_tsv: "tmp/tmp_table.tsv"
  tmp_downloads: "tmp/downloads"
  tmp_fetch: "tmp/fetch_references.txt"
  tmp_acc: "tmp/accessions.txt"
  tmp_fasta3: "tmp/tmp3.fasta"
  tmp_fasta4: "tmp/tmp4.fasta"

modules: 
  generate_alignment_stats: "modules/generate_alignment_stats.R"
  reactable_functions: "modules/reactable_functions.R"
  reactable_columns: "modules/reactable_columns.R"
  
widgets:
  depth_summary: "widgets/depth_summary.R"

microbiome:
  setup_dir: "setup/microbiome"
  first_use_packages: "setup/microbiome/packages_first_use.R"
  tax4fun: "/Users/shayda/Desktop/kegg/Tax4Fun2_ReferenceData_v2/"
  Ref99NR: "/Users/shayda/Desktop/kegg/Tax4Fun2_ReferenceData_v2/Ref99NR/"
  blast: "/Users/shayda/Desktop/kegg/ncbi-blast-2.16.0+-x64-win64/ncbi-blast-2.16.0+/bin/"
  test_prediction: "setup/microbiome/test_prediction/"

swan:
  functions: "setup/read_processing/functions.R"
  marm_tax: "/work/richlab/azadmanesh/marm_bioinfo/data/taxonomy/"
  uid_file: "/work/richlab/azadmanesh/marm_bioinfo/tmp/fetch_references.txt"
  logs: "/work/richlab/azadmanesh/marm_bioinfo/logs"
  ont_reads: "/work/richlab/azadmanesh/ont_reads/"
  dorado_model_r9: "/work/richlab/azadmanesh/ont_reads/dna_r9.4.1_e8_sup@v3.6/"
  dorado_model_r10: "/work/richlab/azadmanesh/ont_reads/dna_r10.4.1_e8.2_400bps_sup@v5.0.0/"
  bioinformatics_stats: "/work/richlab/azadmanesh/marm_bioinfo"
  samplesheets: "/work/richlab/azadmanesh/marm_bioinfo/dataframes/sample_sheets"
  scripts: "/work/richlab/azadmanesh/marm_bioinfo/batch_scripts/"
  accessions: "/work/richlab/azadmanesh/marm_bioinfo/tmp/accessions.txt"
  tmp_fasta1: "/work/richlab/azadmanesh/marm_bioinfo/tmp/tmp1.fasta"
  tmp_fasta2: "/work/richlab/azadmanesh/marm_bioinfo/tmp/tmp2.fasta"
  tmp_fasta3: "/work/richlab/azadmanesh/marm_bioinfo/tmp/tmp3.fasta"
  tmp_fasta4: "/work/richlab/azadmanesh/marm_bioinfo/tmp/tmp4.fasta"
  raw_marm_mb: "/work/richlab/azadmanesh/ont_reads/marm_raw"
  basecalled_marm_mb: "/work/richlab/azadmanesh/ont_reads/basecalled"
  trimmed_marm_mb: "/work/richlab/azadmanesh/ont_reads/trimmed"
  filtered_marm_mb: "/work/richlab/azadmanesh/ont_reads/filtered"
  marm_mb_aligned: "/work/richlab/azadmanesh/marm_bioinfo/data/taxonomy/refseqs_aligned.fasta"
  marm_mb_tree: "/work/richlab/azadmanesh/marm_bioinfo/data/taxonomy/refseqs_tree.newick"

marmoset:
  subjects: "metadata/marm_subjects.tsv"
  samples: "metadata/marm_samples.tsv"
  extracts: "metadata/marm_extracts.tsv"
  libraries: "metadata/marm_libraries.tsv"
  seqruns: "metadata/marm_seqruns.tsv"
  weights: "metadata/marm_weights.tsv"
  leftover_food: "metadata/marm_leftover_food.tsv"
  bristol: "metadata/marm_bristol.tsv"
  compilation: "metadata/marmoset_compilation.tsv"
  subjects_csv: "data/marmoset_subects.csv"
  libraries_csv: "data/libraries_marmoset.csv"
  seqruns_csv: "data/seqruns_marmoset.csv"
  compilation_csv: "data/compilation_marmoset.csv"
  extracts_csv: "data/extracts_marmoset.csv"
  samples_csv: "data/samples_marmoset.csv"
  barcodes_output: "dataframes/barcodes/marmoset/"
  read_alignments: "data/read_alignments/"
  barcode_alignments: "data/barcode_alignments/"
  sample_sheets: "dataframes/sample_sheets/"
  sample_table: "data/metadata"
  taxonomy_list: "data/taxonomy/tax_table.tsv"
  refseq_tree: "data/taxonomy/refseqs_tree.newick"
  refseq_fasta: "data/taxonomy/refseqs_aligned.fasta"
  microeco:
    data:
      main: "microeco/datasets/dataset_main"
      g1: "microeco/datasets/dataset_group1"
      g2: "microeco/datasets/dataset_group2"
      int: "microeco/datasets/dataset_intervention"
      lsk: "microeco/datasets/dataset_ligation"
      rap: "microeco/datasets/dataset_rapid"
      rap_g1: "microeco/datasets/dataset_rapid_group1"
      rap_g2: "microeco/datasets/dataset_rapid_group2"
      rap_int: "microeco/datasets/dataset_rapid_intervention"
      keg:
        main: "microeco/datasets/keg_main"
        g1: "microeco/datasets/keg_group1"
        g2: "microeco/datasets/keg_group2"
        int: "microeco/datasets/keg_intervention"
        lsk: "microeco/datasets/keg_ligation"
        rap: "microeco/datasets/keg_rapid"
        rap_g1: "microeco/datasets/keg_rapid_g1"
        rap_g2: "microeco/datasets/keg_rapid_g2"
        rap_int: "microeco/datasets/keg_rapid_intervention"
      fpt:
        main: "microeco/datasets/fpt_main"
        g1: "microeco/datasets/fpt_group1"
        g2: "microeco/datasets/fpt_group2"
        int: "microeco/datasets/fpt_intervention"
        lsk: "microeco/datasets/fpt_ligation"
        rap: "microeco/datasets/fpt_rapid"
        rap_g1: "microeco/datasets/fpt_rapid_g1"
        rap_g2: "microeco/datasets/fpt_rapid_g2"
        rap_int: "microeco/datasets/fpt_rapid_intervention"
      njc:
        main: "microeco/datasets/njc_main"
        g1: "microeco/datasets/njc_group1"
        g2: "microeco/datasets/njc_group2"
        int: "microeco/datasets/njc_intervention"
        lsk: "microeco/datasets/njc_ligation"
        rap: "microeco/datasets/njc_rapid"
        rap_g1: "microeco/datasets/njc_rapid_g1"
        rap_g2: "microeco/datasets/njc_rapid_g2"
        rap_int: "microeco/datasets/njc_rapid_intervention"
    abund:
      main: "microeco/abundance/main"
      g1: "microeco/abundance/group1"
      g2: "microeco/abundance/group2"
      int: "microeco/abundance/intervention"
      lsk: "microeco/abundance/ligation"
      rap: "microeco/abundance/rapid"
      rap_g1: "microeco/abundance/rapid_g1"
      rap_g2: "microeco/abundance/rapid_g2"
      rap_int: "microeco/abundance/rapid_intervention"
      keg:
        main: "microeco/abundance/keg_main"
        g1: "microeco/abundance/keg_group1"
        g2: "microeco/abundance/keg_group2"
        int: "microeco/abundance/keg_intervention"
        lsk: "microeco/abundance/keg_ligation"
        rap: "microeco/abundance/keg_rapid"
        rap_g1: "microeco/abundance/keg_rapid_g1"
        rap_g2: "microeco/abundance/keg_rapid_g2"
        rap_int: "microeco/abundance/keg_rapid_intervention"
      fpt:
        main: "microeco/abundance/fpt_main"
        g1: "microeco/abundance/fpt_group1"
        g2: "microeco/abundance/fpt_group2"
        int: "microeco/abundance/fpt_intervention"
        lsk: "microeco/abundance/fpt_ligation"
        rap: "microeco/abundance/fpt_rapid"
        rap_g1: "microeco/abundance/fpt_rapid_g1"
        rap_g2: "microeco/abundance/fpt_rapid_g2"
        rap_int: "microeco/abundance/fpt_rapid_intervention"
      njc:
        main: "microeco/abundance/njc_main"
        g1: "microeco/abundance/njc_group1"
        g2: "microeco/abundance/njc_group2"
        int: "microeco/abundance/njc_intervention"
        lsk: "microeco/abundance/njc_ligation"
        rap: "microeco/abundance/njc_rapid"
        rap_g1: "microeco/abundance/njc_rapid_g1"
        rap_g2: "microeco/abundance/njc_rapid_g2"
        rap_int: "microeco/abundance/njc_rapid_intervention"
    alpha:
      main: "microeco/alphadiversity/main"
      g1: "microeco/alphadiversity/group1"
      g2: "microeco/alphadiversity/group2"
      int: "microeco/alphadiversity/intervention"
      lsk: "microeco/alphadiversity/ligation"
      rap: "microeco/alphadiversity/rapid"
      rap_g1: "microeco/alphadiversity/rapid_group1"
      rap_g2: "microeco/alphadiversity/rapid_group2"
      rap_int: "microeco/alphadiversity/rapid_intervention"
      keg:
        main: "microeco/alphadiversity/keg_main"
        g1: "microeco/alphadiversity/keg_group1"
        g2: "microeco/alphadiversity/keg_group2"
        int: "microeco/alphadiversity/keg_intervention"
        lsk: "microeco/alphadiversity/keg_ligation"
        rap: "microeco/alphadiversity/keg_rapid"
        rap_g1: "microeco/alphadiversity/keg_rapid_g1"
        rap_g2: "microeco/alphadiversity/keg_rap_g2"
        rap_int: "microeco/alphadiversity/keg_rapid_intervention"
      fpt:
        main: "microeco/alphadiversity/fpt_main"
        g1: "microeco/alphadiversity/fpt_group1"
        g2: "microeco/alphadiversity/fpt_group2"
        int: "microeco/alphadiversity/fpt_intervention"
        lsk: "microeco/alphadiversity/fpt_ligation"
        rap: "microeco/alphadiversity/fpt_rapid"
        rap_g1: "microeco/alphadiversity/fpt_rapid_g1"
        rap_g2: "microeco/alphadiversity/fpt_rapid_g2"
        rap_int: "microeco/alphadiversity/fpt_rapid_intervention"
      njc:
        main: "microeco/alphadiversity/njc_main"
        g1: "microeco/alphadiversity/njc_group1"
        g2: "microeco/alphadiversity/njc_group2"
        int: "microeco/alphadiversity/njc_intervention"
        lsk: "microeco/alphadiversity/njc_ligation"
        rap: "microeco/alphadiversity/njc_rapid"
        rap_g1: "microeco/alphadiversity/njc_rapid_g1"
        rap_g2: "microeco/alphadiversity/njc_rapid_g2"
        rap_int: "microeco/alphadiversity/njc_rapid_intervention"
    beta:
      main: "microeco/betadiversity/main"
      g1: "microeco/betadiversity/group1"
      g2: "microeco/betadiversity/group2"
      int: "microeco/betadiversity/intervention"
      lsk: "microeco/betadiversity/ligation"
      rap: "microeco/betadiversity/rapid"
      rap_g1: "microeco/betadiversity/rapid_group1"
      rap_g2: "microeco/betadiversity/rapid_group2"
      rap_int: "microeco/betadiversity/rapid_intervention"
      keg:
        main: "microeco/betadiversity/keg_main"
        g1: "microeco/betadiversity/keg_group1"
        g2: "microeco/betadiversity/keg_group2"
        int: "microeco/betadiversity/keg_intervention"
        lsk: "microeco/betadiversity/keg_ligation"
        rap: "microeco/betadiversity/keg_rapid"
        rap_g1: "microeco/betadiversity/keg_rapid_g1"
        rap_g2: "microeco/betadiversity/keg_rapid_g2"
        rap_int: "microeco/betadiversity/keg_rapid_intervention"
      fpt:
        main: "microeco/betadiversity/fpt_main"
        g1: "microeco/betadiversity/fpt_group1"
        g2: "microeco/betadiversity/fpt_group2"
        int: "microeco/betadiversity/fpt_intervention"
        lsk: "microeco/betadiversity/fpt_ligation"
        rap: "microeco/betadiversity/fpt_rapid"
        rap_g1: "microeco/betadiversity/fpt_rapid_g1"
        rap_g2: "microeco/betadiversity/fpt_rapid_g2"
        rap_int: "microeco/betadiversity/fpt_rapid_intervention"
      njc:
        main: "microeco/betadiversity/njc_main"
        g1: "microeco/betadiversity/njc_group1"
        g2: "microeco/betadiversity/njc_group2"
        int: "microeco/betadiversity/njc_intervention"
        lsk: "microeco/betadiversity/njc_ligation"
        rap: "microeco/betadiversity/njc_rapid"
        rap_g1: "microeco/betadiversity/njc_rapid_g1"
        rap_g2: "microeco/betadiversity/njc_rapid_g2"
        rap_int: "microeco/betadiversity/njc_rapid_intervention"

sample_sheets:
  compilations:
    marmoset: "dataframes/sample_sheets/cm_combined_sample_sheet.csv"
  cm001: "dataframes/sample_sheets/cm001_sample_sheet.csv"
  cm002: "dataframes/sample_sheets/cm002_sample_sheet.csv"
  cm003: "dataframes/sample_sheets/cm003_sample_sheet.csv"
  cm004: "dataframes/sample_sheets/cm004_sample_sheet.csv"
  cm005: "dataframes/sample_sheets/cm005_sample_sheet.csv"
  cm006: "dataframes/sample_sheets/cm006_sample_sheet.csv"
  cm007: "dataframes/sample_sheets/cm007_sample_sheet.csv"
  cm008: "dataframes/sample_sheets/cm008_sample_sheet.csv"
  cm009: "dataframes/sample_sheets/cm009_sample_sheet.csv"
  cm010: "dataframes/sample_sheets/cm010_sample_sheet.csv"
  cm011: "dataframes/sample_sheets/cm011_sample_sheet.csv"
  cm012: "dataframes/sample_sheets/cm012_sample_sheet.csv"
  cm013: "dataframes/sample_sheets/cm013_sample_sheet.csv"
  cm014: "dataframes/sample_sheets/cm014_sample_sheet.csv"

barcode_alignments:
  compilations:
    marmoset: "../data/barcode_alignments/cm_combined_barcode_alignment.tsv"
  cm001: "../data/barcode_alignments/cm001_barcode_alignment.tsv"
  cm002: "../data/barcode_alignments/cm002_barcode_alignment.tsv"
  cm003: "../data/barcode_alignments/cm003_barcode_alignment.tsv"
  cm004: "../data/barcode_alignments/cm004_barcode_alignment.tsv"
  cm005: "../data/barcode_alignments/cm005_barcode_alignment.tsv"
  cm006: "../data/barcode_alignments/cm006_barcode_alignment.tsv"
  cm007: "../data/barcode_alignments/cm007_barcode_alignment.tsv"
  cm008: "../data/barcode_alignments/cm008_barcode_alignment.tsv"
  cm009: "../data/barcode_alignments/cm009_barcode_alignment.tsv"
  cm010: "../data/barcode_alignments/cm010_barcode_alignment.tsv"
  cm011: "../data/barcode_alignments/cm011_barcode_alignment.tsv"
  cm012: "../data/barcode_alignments/cm012_barcode_alignment.tsv"
  cm013: "../data/barcode_alignments/cm013_barcode_alignment.tsv"
  cm014: "../data/barcode_alignments/cm014_barcode_alignment.tsv"

abund_wf16s_files:
  cm001: "data/wf16s_abundance/cm001_abundance_table_species.tsv"
  cm002: "data/wf16s_abundance/cm002_abundance_table_species.tsv"
  cm003: "data/wf16s_abundance/cm003_abundance_table_species.tsv"
  cm004: "data/wf16s_abundance/cm004_abundance_table_species.tsv"
  cm005: "data/wf16s_abundance/cm005_abundance_table_species.tsv"
  cm006: "data/wf16s_abundance/cm006_abundance_table_species.tsv"
  cm007: "data/wf16s_abundance/cm007_abundance_table_species.tsv"
  cm008: "data/wf16s_abundance/cm008_abundance_table_species.tsv"
  cm009: "data/wf16s_abundance/cm009_abundance_table_species.tsv"
  cm010: "data/wf16s_abundance/cm010_abundance_table_species.tsv"
  cm011: "data/wf16s_abundance/cm011_abundance_table_species.tsv"
  cm012: "data/wf16s_abundance/cm012_abundance_table_species.tsv"
  cm013: "data/wf16s_abundance/cm013_abundance_table_species.tsv"
  cm014: "data/wf16s_abundance/cm014_abundance_table_species.tsv"

methods_16s:
  libprep_workflow: "'rapid16s'"
  dorado_model_r9: "'dna_r9.4.1_e8_sup@v3.6'"
  dorado_model_r10: "'dna_r10.4.1_e8.2_400bps_sup@v5.0.0'"
  min_length: 1000
  max_length: 2000
  min_qual: 7
  min_id: 85
  min_cov: 80
  kit_name_v9: "'SQK-16S024'"
  kit_name_v14: "'SQK-16S114-24'"
  tax_rank: "S"
  n_taxa_barplot: 12
  abund_threshold: 0
  marm:
    rarefy: 4500
    lsk_rarefy: 6000
    rap_rarefy: 4500
    norm: "SRS"
    min_abund: 0.00001
    min_freq: 1
    include_lowest: TRUE
    unifrac: TRUE
    loris_betadiv: "aitchison"
    alpha_pd: TRUE
    tax4fun_db: "Ref99NR"
    loris_rarefy: 4500
    keg_minID: 97