---
title: "Experiment Metadata"
output:
   html_notebook:
     code_folding: hide
  editor_options:
  chunk_output_type: inline
---

```{r, warning = FALSE}
global <- config::get(config = "default")

here::i_am("Exp_Metadata_2025-6-8_SA.Rmd")
source(here::here(global$setup))
```

# Metadata {.tabset}

## Subjects

```{r}
subjects <- read.table("metadata/subjects.tsv",
                      header = T,
                      sep = "\t") %>%
  kbl() %>%
  kable_styling()
subjects
```

## Samples

```{r}
samples <- read.table("metadata/samples.tsv",
                      header = T,
                      sep = "\t") %>%
  kbl() %>%
  kable_styling()
samples
```

## Extracts

```{r}
extracts <- read.table("metadata/extracts.tsv",
                      header = T,
                      sep = "\t") %>%
  kbl() %>%
  kable_styling()
extracts
```

## Libraries

```{r}
libraries <- read.table("metadata/libraries.tsv",
                      header = T,
                      sep = "\t") %>%
  kbl() %>%
  kable_styling()
libraries
```

## Sequencing Runs

```{r}
seqruns <- read.table("metadata/seqruns.tsv",
                      header = T,
                      sep = "\t") %>%
  kbl() %>%
  kable_styling()
seqruns
```

## Weights

```{r}
weights <- read.table("metadata/weights.tsv",
                      header = T,
                      sep = "\t") %>%
  kbl() %>%
  kable_styling()
weights
```

## Leftover Food

```{r}
leftover_food <- read.table("metadata/leftover_food.tsv",
                      header = T,
                      sep = "\t") %>%
  kbl() %>%
  kable_styling()
leftover_food
```

## Bristol

```{r}
bristol <- read.table("metadata/bristol.tsv",
                      header = T,
                      sep = "\t") %>%
  kbl() %>%
  kable_styling()
bristol
```
