---
title: "Marm_Metadata_2025-6-4_SA"
author: "Shayda"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
global <- config::get(config = "default")

here::i_am("Marm_Metadata_2025-6-4_SA.Rmd")
source(here::here(global$setup))

```
# Metadata
```{r}
subjects <- read.table(marmoset$subjects,
                      header = T,
                      sep = "\t") %>%
  mutate(
    Room = str_glue("Room{str_extract(Cage, '^[a-zA-Z]')}"),
    Subject_Code = factor(Subject_Code, levels = unique(Subject_Code)),
    Subject = factor(Subject, levels = unique(Subject)),
    Sex = factor(Sex, levels = unique(Sex)),
    Housing = factor(Housing, levels = unique(Housing)),
    Group = factor(Group, levels = unique(Group)),
    Subj_DOB = as.Date(DOB, format = "%m/%d/%y"),
    Room = factor(Room, levels = unique(Room))
  ) %>%
  dplyr::select(Group,
                Room,
                Cage,
                Subject,
                Subject_Code,
                Sex,
                Housing,
                Origin,
                Subj_DOB,
                Age,
                Contraception,
                Previous_Exp,
                Subject_Notes
                )
```
```{r}
write.csv(subjects, "metadata/subjects.csv")
write.table(subjects, file = "metadata/subjects.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
```
```{r}
samples <- read.table(marmoset$samples,
                      header = T,
                      sep = "\t") %>%
  mutate(Date = as.Date(Sample_Date,
                        format = "%m/%d/%y"),
         Study_Day = str_extract(Sample_ID, "(?<=-)[0-9]+(?=-)"),
         Subj_Day = fct(str_glue("{Subject}", "_", "{Study_Day}")),
         SampleTimeFormatted = str_pad(Sample_Time, 4, pad = "0"),
         Sample_Time = as_hms(sprintf("%02d:%02d:00",
          as.integer(str_sub(SampleTimeFormatted, 1, 2)),
          as.integer(str_sub(SampleTimeFormatted, 3, 4))))) %>%
  dplyr::select(Sample_ID,
                Date,
                Study_Day,
                Sample_Time,
                Subject,
                Sample_Collected_By,
                Bristol,
                Sample_Stabilizer,
                Sample_Box,
                Sample_Notes,
                Diet_Trial,
                Group_Phase,
                Subj_Day,
                Known_Repro
                )
```
```{r}
write.csv(samples, "metadata/samples.csv")
write.table(samples, file = "metadata/samples.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
```
```{r}
extracts <- read.table(marmoset$extracts,
                      header = T,
                      sep = "\t") %>%
  mutate(Extract_Date = as.Date(Extract_Date,
                               format = "%m/%d/%y"),
         Extract_Conc_ng_uL = Extract_Conc_.ng.uL.) %>%
  dplyr::select(Extract_ID,
                Sample_ID,
                Extract_Type,
                Extract_Date,
                Extracted_By,
                Extract_Conc_ng_uL,
                Extract_Kit,
                Extract_Box,
                Extract_Notes
                )
```
```{r}
write.csv(extracts, "metadata/extracts.csv")
write.table(extracts, file = "metadata/extracts.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
```
```{r}
libraries <- read.table(marmoset$libraries,
                      header = T,
                      sep = "\t") %>%
  mutate(Final_Lib_Conc_ng_uL = Final_Lib_Conc_.ng.uL.,
         Vol_Added_Pool_uL = Vol_Added_Pool_.uL.) %>%
  dplyr::select(Sequence_ID,
                Extract_ID,
                Sample_ID,
                Seq_ID,
                Library_Tube,
                Library_Tube_ID,
                Library_Barcode,
                F_Primer,
                R_Primer,
                Run_ID,
                Final_Lib_Conc_ng_uL,
                Vol_Added_Pool_uL
                )
```
```{r}
write.csv(libraries, "metadata/libraries.csv")
write.table(libraries, file = "metadata/libraries.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
```
```{r}
seqruns <- read.table(marmoset$seqruns,
                      header = T,
                      sep = "\t") %>%
  mutate(Run_Date = as.Date(Run_Date,
                               format = "%m/%d/%y"),
         Seq_ID = Pooled_Library_Code,
         Full_Seq_ID = Pooled_Library_ID) %>%
  dplyr::select(Run_ID,
                Full_Seq_ID,
                Seq_ID,
                Pipeline,
                Kit,
                Sequencer,
                MinION_Position,
                Flow_Cell_Type,
                Flongle_Adapter,
                Flow_Cell_ID,
                Run_Date,
                Loaded_By
                )
```
```{r}
write.csv(seqruns, "metadata/seqruns.csv")
write.table(seqruns, file = "metadata/seqruns.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
```
```{r}
weights <- read.table(marmoset$weights,
                      header = T,
                      sep = "\t") %>%
  mutate(Date = as.Date(Date,
                        format = "%m/%d/%y")) %>%
  dplyr::select(Date,
                Study_Day,
                Subject,
                Weight_g,
                Weight_Collected_By,
                Weight_Notes)
```
```{r}
write.csv(weights, "metadata/weights.csv")
write.table(weights, file = "metadata/weights.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
```
```{r}
leftover_food <- read.table(marmoset$leftover_food,
                      header = T,
                      sep = "\t") %>%
  mutate(Date = as.Date(Date,
                                format = "%m/%d/%y"),
         Leftover_Gel_Zupreem = Gel.Zupreem,
         Leftover_Apple = Apple,
         Leftover_Sweet_Potato = Sweet_Potato,
         Leftover_Eggs = Eggs) %>%
  dplyr::select(Date,
                Cage,
                Leftover_Gel_Zupreem,
                Leftover_Apple,
                Leftover_Sweet_Potato,
                Leftover_Eggs,
                Diet_Notes)
```
```{r}
write.csv(leftover_food, "metadata/leftover_food.csv")
write.table(leftover_food, file = "metadata/leftover_food.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
```
```{r}
bristol <- read.table(marmoset$bristol,
                      header = T,
                      sep = "\t") %>%
  mutate(Date = as.Date(Date,
                                format = "%m/%d/%y")) %>%
  dplyr::select(Date,
                Subject,
                Bristol, 
                Repro_Status
                )
```
```{r}
write.csv(bristol, "metadata/bristol.csv")
write.table(bristol, file = "metadata/bristol.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
```
```{r}
samp_subj <- samples %>%
  left_join(subjects, by = "Subject")
```
```{r}
seq_metadata <- libraries %>%
  left_join(seqruns, by = c("Seq_ID", "Run_ID"))
```
```{r}
full_metadata <- samp_subj %>%
  left_join(extracts, by = "Sample_ID") %>%
  left_join(seq_metadata, by = c("Extract_ID", "Sample_ID"))
```
```{r}
write.csv(full_metadata, "metadata/full_metadata.csv")
write.table(full_metadata, file = "metadata/full_metadata.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
```
```{r}
metadata <- seq_metadata %>%
  left_join(extracts, by = c("Extract_ID", "Sample_ID")) %>%
  left_join(samp_subj, by = c("Sample_ID"))
```
```{r}
write.csv(metadata, "metadata/metadata.csv")
write.table(metadata, file = "metadata/metadata.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
```