#!/bin/bash
#SBATCH --time=2:00:00
#SBATCH --job-name=basecall_cm007
#SBATCH --error=/work/richlab/azadmanesh/marm_bioinfo/logs/basecall_cm007_%A_%a.err
#SBATCH --output=//work/richlab/azadmanesh/marm_bioinfo/logs/basecall_cm007_%A_%a.out
#SBATCH --partition=gpu,guest_gpu
#SBATCH --constraint='gpu_v100|gpu_t4'
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=200GB
#SBATCH --gres=gpu:1

module purge
module load dorado-gpu/0.7

pod5="/work/richlab/azadmanesh/marm_bioinfo/ont_reads/marm_raw/cm007/"
basecalled="/work/richlab/azadmanesh/marm_bioinfo/ont_reads/basecalled/cm007/"


algo="/work/richlab/azadmanesh/marm_bioinfo/ont_reads/dna_r9.4.1_e8_sup@v3.6/"

dorado basecaller "$algo" \
"$pod5" \
--recursive \
--no-trim \
> "$basecalled/cm007.bam" && \
dorado summary "$basecalled/cm007.bam" > "$basecalled/cm007_basecall_summary.tsv"
