#!/bin/bash
#SBATCH --time=2:00:00
#SBATCH --job-name=basecall_cm011
#SBATCH --error=/work/richlab/azadmanesh/marm_bioinfo/logs/basecall_cm011_%A_%a.err
#SBATCH --output=//work/richlab/azadmanesh/marm_bioinfo/logs/basecall_cm011_%A_%a.out
#SBATCH --partition=gpu,guest_gpu
#SBATCH --constraint='gpu_v100|gpu_t4'
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=200GB
#SBATCH --gres=gpu:1

module purge
module load dorado-gpu/0.7

pod5="/work/richlab/azadmanesh/marm_bioinfo/ont_reads/marm_raw/cm011/"
basecalled="/work/richlab/azadmanesh/marm_bioinfo/ont_reads/basecalled/cm011/"

algo="/work/richlab/azadmanesh/marm_bioinfo/ont_reads/dna_r10.4.1_e8.2_400bps_sup@v5.0.0/"

dorado basecaller "$algo" \
"$pod5" \
--recursive \
--no-trim \
> "$basecalled/cm011.bam" && \
dorado summary "$basecalled/cm011.bam" > "$basecalled/cm011_basecall_summary.tsv"
