#!/bin/bash
#SBATCH --time=00:45:00
#SBATCH --job-name=qc_cm002
#SBATCH --error=/work/richlab/azadmanesh/marm_bioinfo/logs/qc_cm002_%A_%a.err
#SBATCH --output=/work/richlab/azadmanesh/marm_bioinfo/logs/qc_cm002_%A_%a.out
#SBATCH --partition=guest
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=100GB

module purge
module load anaconda

conda activate filter

trimmed="/work/richlab/azadmanesh/marm_bioinfo/ont_reads/trimmed/cm002/"
filtered="/work/richlab/azadmanesh/marm_bioinfo/ont_reads/filtered/cm002/"

cd $trimmed

for file in "$trimmed"/*.fastq; do
    
    if [ -f "$file" ]; then
       
        base_filename=$(basename "$file")

        chopper --maxlength 2000 --minlength 1000 --quality 7 --input "$file" > "$filtered/$base_filename"

        echo "Processed $file"
    else
        echo "Error: File $file does not exist or is not a regular file."
    fi
done

cd $filtered

for file in "$filtered"/*.fastq; do
    if [ -f "$file" ]; then
        base_filename=$(basename "$file" .fastq)
        
        mkdir -p "$filtered/$base_filename"
        
        mv "$file" "$filtered/$base_filename/${base_filename}.fastq"
        
        echo "Organized $file"
    else
        echo "Error: File $file does not exist or is not a regular file."
    fi
done
